#!/bin/sh

# with 4k display plugged into hdmi port

# need to disable one of the screeens -- can only support 3 (at this resolution at least).  For now do that manually in display-settings at the end.

# also -- positioning!  & primary-ness

xrandr --nograb --newmode "4k_sh"x0.0  297.00  3840 4016 4104 4400  2160 2168 2178 2250 +hsync +vsync

xrandr --nograb --newmode 4k_sh 297.00  3840 4016 4104 4400  2160 2168 2178 2250 +hsync +vsync
xrandr --nograb --addmode HDMI-1 "4k_sh"
# xrandr --nograb

xrandr --output eDP-1 --mode 1920x1080 --pos 4480x360 --primary --output HDMI-1 --mode 4k_sh --pos 0x360

xfce4-display-settings &




