#!/bin/sh

TARGET=$1

if [ "$TARGET" = "" ]; then
    echo Usage: $0 HOSTNAME
    exit 1
fi

# maybe send different files to different types of hosts?
#
# for now, we only set up generic https nginx servers

scp ~/bin/set-me-up.sh ~/bin/set-me-up.nginx root@$TARGET:
ssh root@$TARGET "export HOST=$TARGET; export EMAIL=sandro@hawke.org; sh set-me-up.sh" 
curl https://$TARGET
echo
echo CONSIDER:
echo 
echo opn https://$TARGET
echo configure-server-pm2 $TARGET
echo push-to-server $TARGET
echo push-to-server-pm2 $TARGET $PORT $PATH
echo
