#!/bin/sh

# where can we pull this from?  It's needed for letsencrypt
EMAIL=sandro@hawke.org

#
# Should be okay to run multiple times, and with shared servers, once
# for each name
#

if [ "$TARGET" = "" ]; then
    TARGET=$1
fi

if [ "$TARGET" = "" ]; then
    echo Usage: $0 HOSTNAME
    exit 1
fi

USER=$LOGNAME

# maybe send different files to different types of hosts?
#
# for now, we only set up generic https nginx servers

cd $(dirname $0) || exit 1
scp set-me-up-static.sh add-host.sh set-me-up-static.nginx root@$TARGET: || exit 1
ssh root@$TARGET "export HOST=$TARGET EMAIL=$EMAIL USER=$USER; sh set-me-up-static.sh; sh add-host.sh $TARGET" || exit 1
curl https://$TARGET
echo
echo Now add hosts to it
echo
