#!/bin/sh

if [ "$TARGET" = "" ]; then
    TARGET=$1
fi

if [ "$TARGET" = "" ]; then
    echo Usage: $0 HOSTNAME
    exit 1
fi

# maybe send different files to different types of hosts?
#
# for now, we only set up generic https nginx servers

cd $(dirname $0) || exit 1
scp set-me-up.sh set-me-up.nginx root@$TARGET: || exit 1
ssh root@$TARGET "export HOST=$TARGET; export EMAIL=sandro@hawke.org; sh set-me-up.sh" || exit 1
curl https://$TARGET
echo
echo CONSIDER:
echo 
echo "opn https://$TARGET"
echo "configure-server-pm2 $TARGET      # for node.js + pm2"
echo "configure-server-app $TARGET      # tell nginx to proxy"
echo push-to-server
echo
