#!/usr/bin/env bun

import { readFileSync } from "fs";
import { join } from "path";

const pkgPath = process.argv[2];

if (!pkgPath) {
  console.error("Usage: count-deps <path-to-package>");
  process.exit(1);
}

let packageJsonPath = pkgPath;
if (!packageJsonPath.endsWith("package.json")) {
  packageJsonPath = join(pkgPath, "package.json");
}

let pkg;
try {
  pkg = JSON.parse(readFileSync(packageJsonPath, "utf8"));
} catch (err) {
  console.error(`Failed to read ${packageJsonPath}`);
  process.exit(1);
}

const sections = [
  "dependencies",
  "devDependencies",
  "peerDependencies",
  "optionalDependencies",
];

const allDeps = sections.flatMap(section =>
  Object.keys(pkg[section] ?? {})
);

const uniqueDeps = new Set(allDeps);

console.log(uniqueDeps.size);