#!/bin/bash
#
# get your key at https://cloud.digitalocean.com/account/api/tokens
#
# then
#   export DIGOCTOK=...
# then
#   digoc-reset-ip domain
#
#
DOMAIN=$1
if [ -z "$DOMAIN" ]; then
  echo usage: DIGOCTOK="..." $0 domain.name
  exit 1
fi

curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DIGOCTOK" "https://api.digitalocean.com/v2/domains/$DOMAIN/records" | jq

