#!/bin/bash

echo -e '\n\n\n\n'
clear

cd ~/Repos

# all the repos that have had json or js activity in the past 45 days

for x in $(find */*.json */*.js */*.md -mtime -60 | sed 's;/.*;;' | sort | uniq)
do
    if [ -f $x/UNMAINTAINED* ]; then
        unm="$unm $x"
        # echo $x unmaintained 
        continue;
    fi
    if git -C $x diff-index --quiet HEAD -- && git -C $x status -s; then
        echo "$(tput setaf 0)$(tput sgr 7)$(tput bold) $x $(tput sgr0)"
        git -C $x log -n 1 --oneline
    else
        echo "$(tput setaf 0)$(tput sgr 7)$(tput bold)$(tput setaf 1) $x $(tput sgr0) uncommitted changes"
        echo "cd ~/r/$x; git diff"
        git -C $x status -s
        echo
fi

done

echo
echo flagged as unmaintained: $unm
