#!/bin/bash
#
# get your key at https://developer.godaddy.com/keys/
#
# then
#   export KEY="key:secret"
#   (the key part is what shows up under Production, the secret part
#   you have to know from when you created it)
# then
#   goaddy-add-mailgun DOMAIN STRING-STARTING-k=rsa;p=...
#
#
RSA=$2
DOMAIN=$1
if [ -z "$RSA" -o -z "$DOMAIN" ]; then
  echo usage: KEY="key:secret" $0 domain "string-starting-k=rsa;p="
  exit 1
fi

echo -n BEFORE:
curl -s -X GET -H "Authorization: sso-key $KEY" "https://api.godaddy.com/v1/domains/$DOMAIN/records" | jq
echo

#
#curl -X PUT -k -H "Content-Type: application/json" \
#   -H "Authorization: sso-key $KEY" \
#   --data '{ "type": "TXT", "name": "@", "ttl": 600, "data": "v=spf1 include:ma#ilgun.org ~all" }' \
#   "https://api.godaddy.com/v1/domains/$DOMAIN/records/TXT/%40"

curl -X PUT -k -H "Content-Type: application/json" \
   -H "Authorization: sso-key $KEY" \
   --data '{ "type": "TXT", "name": "_domainkey.'$DOMAIN'", "ttl": 600, "data": "'"style0"'" }' \
   "https://api.godaddy.com/v1/domains/$DOMAIN/records/TXT/%40"


curl -X PUT -k -H "Content-Type: application/json" \
   -H "Authorization: sso-key $KEY" \
   --data '{ "type": "TXT", "name": "mx._domainkey.'$DOMAIN'", "ttl": 600, "data": "'"style1"'" }' \
   "https://api.godaddy.com/v1/domains/$DOMAIN/records/TXT/%40"


curl -X PUT -k -H "Content-Type: application/json" \
   -H "Authorization: sso-key $KEY" \
   --data '{ "type": "TXT", "name": "@", "ttl": 600, "data": "'"style2"'" }' \
   "https://api.godaddy.com/v1/domains/mx._domainkey.$DOMAIN/records/TXT/%40"


echo
echo
echo -n AFTER:
curl -s -X GET -H "Authorization: sso-key $KEY" "https://api.godaddy.com/v1/domains/$DOMAIN/records" | jq
echo

