#!/bin/bash
#
# Change    require('module-I-have-locally')
# to        require('/...path.../module-I-have-locally')
#
# and -u changes is back.

# maybe there's a way to get npm to tell me the files?

R=$HOME/Repos
# things not dir names
MANUAL="live-source-proxy/client live-source-proxy/server flextag-protocol/client flextag-protocol/server"

USAGE="Usage: $0 [-u] *.js"

if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

if [ "$1" == "-u" ]; then
    shift
    UNDO=true
else
    UNDO=false
fi

M=$(cd $R; echo * $MANUAL)

# maybe only do this if git's not super clean?
now=$(date -Is | tr : _)
bakdir=$HOME/.npm-require-local/$PWD
mkdir -p $bakdir
echo making backup tar file in $bakdir
tar czvf $bakdir/$now.tz "$@"

for X in $M; do
    if $UNDO; then
        sed -i -e "s;require('$R/$X');require('$X');g" "$@"
    else
        sed -i -e "s;require('$X');require('$R/$X');g" "$@"
    fi
done
