#!/bin/bash

if [ -z "$1" ]; then
    # List of hostnames to try
    hostnames=(petra venice denali bali banff aspen kyoto cork pisa lyon vail milan dublin lisbon athens berlin oslo zurich cairo tokyo madrid london paris rome denver)
    
    # Get list of existing droplets
    existing=$(doctl compute droplet list --format Name --no-header)
    
    # Find first hostname that doesn't exist
    for hostname in "${hostnames[@]}"; do
        if ! echo "$existing" | grep -q "^$hostname$"; then
            H="$hostname"
            echo "Using hostname: $H"
            break
        fi
    done
    
    if [ -z "$H" ]; then
        echo "Error: All hostnames are already in use"
        exit 1
    fi
else
    H="$1"
fi

IMAGE=196091866
# IMAGE=195441144 
# SIZE=s-1vcpu-1gb
SIZE=s-2vcpu-4gb
time doctl compute droplet create $H --region nyc3 --image $IMAGE --size $SIZE --ssh-keys 49278150 --wait
IP=$(doctl compute droplet list $H --format PublicIPv4 --no-header) && echo IP=$IP && while ! nc -z $IP 22; do sleep 1; done
ssh-name $H $IP

echo adding host key to gitolite permissions for acorn repos
host-allow-git $H

echo $H is up!  Connecting...

ssh $H
