#!/bin/bash

HOST="$1"

if [ -z "$HOST" ]; then
  echo "usage $0 <hostname>"
  exit 1
fi

cat <<_END > /tmp/hist
claude --dangerously-skip-permissions
codex --dangerously-bypass-approvals-and-sandbox
codex --yolo
git clone git@git.wkbl.dev:wkbl
git clone git@git.wkbl.dev:wkbl && cd wkbl
git clone git@git.wkbl.dev:wkbl && cd wkbl && ./DEPLOY.sh
_END

scp /tmp/hist $HOST:.bash_history
